// NODE_PATH must include Playwright. Serve the Atlas on port 8765.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const output = require('node:os').tmpdir();
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE} : {}) });
  try {
    const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    // Test-only instrumentation observes restoration without changing the shipped app.
    await page.route(/\/js\/app\.js(?:\?|$)/, async route => {
      const source = require('node:fs').readFileSync(path.join(__dirname, '../js/app.js'), 'utf8');
      await route.fulfill({contentType:'text/javascript',body:source+`\nwindow.__atlasTestSnapshot = () => ({ size: [state.map.getSize().x,state.map.getSize().y], center: [state.map.getCenter().lat,state.map.getCenter().lng], zoom: state.map.getZoom(), savedCenter: simulatorAtlasView ? [simulatorAtlasView.center.lat,simulatorAtlasView.center.lng] : null, filters: { election: state.targetElection, base: state.baseElection, level: state.mapLevel, indicator: state.indicator, viewMode: state.viewMode, force: state.force, voteType: state.voteType, positiveMeasure: state.positiveMeasure, selectedParty: state.selectedParty, selectedLocality: state.selectedLocality, selectedCircuit: state.selectedCircuit, continuityActive: state.continuityActive, scatterSelection: [...state.scatterSelection] } });`});
    });
    await page.goto('http://127.0.0.1:8765', { waitUntil: 'networkidle' });
    await page.locator('#loading.is-hidden').waitFor({state:'attached'});
    await page.locator('#mapLevelCircuit').click();
    await page.waitForTimeout(250);
    const atlasSnapshot = () => page.evaluate(() => window.__atlasTestSnapshot());
    await page.locator('#mapSearchInput').fill('La Plata');
    await page.locator('#mapSearchResults button').first().click();
    await page.waitForTimeout(300);
    const original = await atlasSnapshot();
    const originalFrame = await page.locator('.map-pane').boundingBox();
    const originalLeft = await page.locator('.workspace-panel .topbar').boundingBox();
    assert.ok(original.filters.selectedCircuit || original.filters.selectedParty, 'start with an Atlas territory selection');
    await page.locator('#openSimulator').click();
    assert.equal(await page.locator('#simKpis .kpi-item').count(), 3);
    assert.match(await page.locator('#simStatus').textContent(), /Todavía/);
    await page.locator('#simShare').evaluate(el=>{el.value='100';el.dispatchEvent(new Event('input',{bubbles:true}));});
    assert.match(await page.locator('#simStatus').textContent(), /potencial provincial suficiente/);
    assert.equal(await page.locator('#simKpis .kpi-item').count(),3);
    await page.locator('#simReset').click();
    assert.match(await page.locator('#simStatus').textContent(), /Todavía/);
    await page.locator('#simForce').selectOption({ index:1 });
    await page.locator('#simShare').evaluate(el=>{el.value='65';el.dispatchEvent(new Event('input',{bubbles:true}));});
    assert.equal(await page.locator('#simShare').inputValue(), '65');
    await page.locator('#simIncrease').check();
    await page.locator('#simTurnout').evaluate(el=>{el.value='80';el.dispatchEvent(new Event('input',{bubbles:true}));});
    const force = await page.locator('#simForce').inputValue();
    await page.screenshot({path:path.join(output, 'simulator-provincial-desktop.png')});
    await page.locator('#simExplore').click();
    await page.waitForTimeout(250);
    assert.equal(await page.locator('.simulator').evaluate(el=>el.open), false);
    assert.equal(await page.locator('body.is-simulator-exploring').count(), 1);
    assert.equal(await page.locator('.leaflet-simulatorExplorer-pane canvas').count(), 1);
    const explorationFrame = await page.locator('.map-pane').boundingBox();
    const explorationLeft = await page.locator('.sim-explorer-controls').boundingBox();
    for (const prop of ['x','y','width','height']) assert.ok(Math.abs(explorationFrame[prop]-originalFrame[prop])<2, `native map frame ${prop}`);
    for (const prop of ['x','y','width']) assert.ok(Math.abs(explorationLeft[prop]-originalLeft[prop])<2, `native controls frame ${prop}`);
    assert.match(await page.locator('[data-mini-comparison]').textContent(), /Observada/);
    assert.match(await page.locator('[data-mini-comparison]').textContent(), /Objetivo/);
    assert.match(await page.locator('[data-mini-comparison]').textContent(), /Votos adicionales necesarios/);
    const varied = await page.locator('.sim-territory-point').evaluateAll(nodes=>new Set(nodes.map(n=>n.getAttribute('r'))).size);
    assert.ok(varied>1,'abstention bubble sizes with turnout increase');
    assert.match(await page.locator('[data-encoding]').textContent(), /abstenciones/);
    await page.locator('[data-log]').check();
    assert.match(await page.locator('.sim-scatter').textContent(), /escala logarítmica/);
    assert.match(await page.locator('.sim-scatter').textContent(), /votantes observados/);
    await page.locator('[data-expand]').click();
    assert.equal(await page.locator('.sim-chart-floating:visible').count(),1);
    assert.equal(await page.locator('.sim-chart-floating').getAttribute('aria-modal'),'false');
    const floatBefore = await page.locator('.sim-chart-floating').boundingBox();
    const header = await page.locator('.sim-chart-floating header h2').boundingBox();
    await page.mouse.move(header.x+20,header.y+10); await page.mouse.down();
    await page.mouse.move(header.x+70,header.y+40,{steps:8}); await page.mouse.up();
    const floatAfter = await page.locator('.sim-chart-floating').boundingBox();
    assert.ok(floatAfter.x>floatBefore.x+30 && floatAfter.y>floatBefore.y+20,'floating chart moves');
    await page.mouse.move(floatAfter.x+floatAfter.width-3,floatAfter.y+floatAfter.height-3); await page.mouse.down();
    await page.mouse.move(floatAfter.x+floatAfter.width-83,floatAfter.y+floatAfter.height-53,{steps:8}); await page.mouse.up();
    const resized = await page.locator('.sim-chart-floating').boundingBox();
    assert.ok(resized.width<floatAfter.width-50 && resized.height<floatAfter.height-30,'floating chart resizes');
    await page.locator('[data-search]').fill('La Plata');
    await page.locator('[data-party-list] label:visible input').check();
    const firstProgress = await page.locator('[data-progress]').evaluate(el=>el.value);
    assert.ok(firstProgress>0 && firstProgress<100);
    await page.locator('[data-search]').fill('Avellaneda');
    await page.locator('[data-party-list] label:visible input').check();
    assert.ok(await page.locator('[data-progress]').evaluate(el=>el.value)>firstProgress,'selection increases potential coverage');
    await page.locator('[data-clear]').click();
    assert.equal(await page.locator('[data-progress]').evaluate(el=>el.value),0);
    await page.locator('[data-search]').fill('');
    await page.screenshot({path:path.join(output, 'simulator-scatter-expanded.png')});
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('body.is-simulator-exploring').count(),1);
    assert.equal(await page.locator('.sim-chart-floating:visible').count(),0);
    const checks = page.locator('[data-party-list] input');
    assert.equal(await checks.count(), 135);
    await page.locator('[data-search]').fill('La Plata');
    assert.equal(await page.locator('[data-party-list] label:visible').count(), 1);
    await page.locator('[data-party-list] label:visible input').check();
    assert.equal(await page.locator('.sim-territory-point.is-selected').count(), 1);
    const key = await page.locator('[data-party-list] input:checked').getAttribute('data-party');
    await page.locator(`[data-key="${key}"]`).focus();
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('[data-party-list] input:checked').count(), 0);
    await page.locator('[data-undo]').click();
    assert.equal(await page.locator('[data-party-list] input:checked').count(), 1);
    await page.locator('[data-clear]').click();
    assert.equal(await page.locator('.sim-territory-point.is-selected').count(), 0);
    await page.locator('[data-search]').fill('');
    // Select on the actual Leaflet canvas, then verify the list and scatter follow it.
    const mapBox = await page.locator('#map').boundingBox();
    for (const [x,y] of [[.5,.5],[.6,.6],[.45,.6],[.6,.4]]) {
      await page.mouse.click(mapBox.x+mapBox.width*x,mapBox.y+mapBox.height*y);
      if (await page.locator('[data-party-list] input:checked').count()) break;
    }
    assert.ok(await page.locator('[data-party-list] input:checked').count()>0, 'map click selects a party');
    assert.equal(await page.locator('.sim-territory-point.is-selected').count(), await page.locator('[data-party-list] input:checked').count());
    await page.locator('[data-clear]').click();
    const svg = page.locator('.sim-scatter');
    await page.locator('[data-lasso]').click();
    await svg.scrollIntoViewIfNeeded();
    const box = await svg.boundingBox();
    // Work in displayed coordinates; the scatter now adapts its viewBox to its panel.
    await page.mouse.move(box.x+2,box.y+2); await page.mouse.down();
    for (const [x,y] of [[box.width-2,2],[box.width-2,box.height-2],[2,box.height-2],[2,2]]) await page.mouse.move(box.x+x,box.y+y,{steps:15});
    await page.mouse.up();
    const count = await page.locator('.sim-territory-point').count();
    assert.ok(count>100);
    assert.equal(await page.locator('.sim-territory-point.is-selected').count(), count);
    assert.equal(await page.locator('[data-party-list] input:checked').count(), count);
    assert.equal(await page.locator('[data-progress]').evaluate(el=>el.value),100);
    assert.match(await page.locator('[data-relation]').textContent(), /potencial suficiente/);
    assert.match(await page.locator('[data-kpis]').textContent(), /Excedente/);
    assert.match(await page.locator('[data-newcomer]').textContent(), /nuevos votantes provinciales/);
    await page.locator('[data-map]').click();
    await page.locator('#simEdit').click();
    assert.equal(await page.locator('#simShare').inputValue(), '65');
    await page.locator('#simReset').click();
    assert.equal(await page.locator('#simForce').inputValue(), force);
    assert.equal(await page.locator('[data-party-list] input:checked').count(), count);
    await page.locator('#simShare').evaluate(el=>{el.value='45';el.dispatchEvent(new Event('input',{bubbles:true}));});
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('body.is-simulator-exploring').count(), 1);
    assert.match(await page.locator('.sim-target-row').textContent(), /45.0%/);
    const equal = await page.locator('.sim-territory-point').evaluateAll(nodes=>new Set(nodes.map(n=>n.getAttribute('r'))).size);
    assert.equal(equal,1,'equal point sizes at unchanged turnout');
    assert.match(await page.locator('[data-encoding]').textContent(), /mismo tamaño/);
    await page.locator('[data-lasso]').click();
    await page.locator('[data-clear]').click();
    await page.locator('[data-search]').fill('La Plata');
    await page.locator('[data-party-list] label:visible input').check();
    await page.locator('[data-zoom]').click();
    assert.ok(await page.locator('.sim-territory-node[tabindex="0"]').count()<135,'zoom narrows visible plot');
    await page.locator('[data-full]').click();
    assert.equal(await page.locator('.sim-territory-node[tabindex="0"]').count(),135);
    assert.match(await page.locator('[data-relation]').textContent(), /votos potenciales/);
    await page.locator('[data-search]').fill('');
    await page.locator('.sim-explorer-controls').evaluate(el=>{el.scrollTop=0;});
    await page.locator('.sim-explorer-chart').evaluate(el=>{el.scrollTop=0;});
    await page.screenshot({path:path.join(output, 'simulator-territory-desktop.png')});
    await page.locator('#simExit').click();
    await page.waitForTimeout(250);
    const restored = await atlasSnapshot();
    assert.deepEqual(restored.filters, original.filters, 'restore previous Atlas filters and selection');
    assert.equal(restored.zoom, original.zoom);
    assert.ok(restored.center.every((v,i)=>Math.abs(v-original.center[i])<.005), `restore previous map center: ${JSON.stringify({original,restored})}`);
    assert.equal(await page.locator('.leaflet-simulatorExplorer-pane canvas').count(), 0);
    await page.locator('#openSimulator').click();
    await page.locator('#simExplore').click();
    assert.equal(await page.locator('[data-party-list] input:checked').count(), 1);
    await page.setViewportSize({width:390,height:844});
    await page.locator('[data-clear]').click();
    await page.locator('[data-search]').fill('La Plata');
    await page.locator('[data-party-list] label:visible input').check();
    assert.equal(await page.locator('.sim-territory-point.is-selected').count(),1);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1), 'mobile page has no horizontal overflow');
    await page.screenshot({path:path.join(output, 'simulator-territory-mobile.png'),fullPage:true});
    assert.ok(await page.locator('.sim-explorer-summary').evaluate(el=>el.scrollHeight<=el.clientHeight+1),'mobile coverage panel shows its complete content');
    await page.locator('[data-expand]').click();
    const mobileFloat = await page.locator('.sim-chart-floating').boundingBox();
    assert.ok(mobileFloat.x>=0 && mobileFloat.x+mobileFloat.width<=390,'mobile floating chart fits');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.sim-chart-floating:visible').count(),0);
    await page.locator('#simEdit').click();
    assert.ok(await page.locator('.simulator').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'mobile dialog fits');
    await page.screenshot({path:path.join(output, 'simulator-provincial-mobile.png')});
    await page.keyboard.press('Escape');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('body.is-simulator-exploring').count(),0);
    assert.deepEqual(errors, []);
    console.log(`OK UI: native frame, baseline/target, voters axis, turnout-dependent sizes, log, zoom, expanded view, three KPIs, exact input, map/list/scatter sync, lasso ${count} parties, undo, persistence, reset, Atlas restoration, Escape and mobile layout.`);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
