const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try {
  const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765/',{waitUntil:'domcontentloaded'});
  await page.locator('#loading.is-hidden').waitFor({state:'attached'});
  await page.locator('#openSimulator').click();
  assert.equal(await page.locator('#simRepeat').isVisible(),false);
  await page.locator('#simIncrease').check();
  assert.equal(await page.locator('#simRepeat').isChecked(),false);
  assert.equal(await page.locator('#simRepeat').isEnabled(),true);
  await page.locator('#simTurnout').evaluate(el=>{el.value='80';el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.locator('#simShare').evaluate(el=>{el.value='100';el.dispatchEvent(new Event('input',{bubbles:true}));});
  const original=await page.locator('#simComparison').textContent();
  await page.locator('#simRepeat').check();
  assert.notEqual(await page.locator('#simComparison').textContent(),original);
  assert.match(await page.locator('#simStatus').textContent(),/faltan/);
  assert.match(await page.locator('#simComposition').textContent(),/distribución provincial/);
  assert.match(await page.locator('#simVoteTypes').textContent(),/blancos.*nulos.*impugnados.*recurridos/);
  const dialog=await page.locator('.simulator').boundingBox(),comparison=await page.locator('.sim-comparison').boundingBox();
  assert.ok(comparison.y+comparison.height<=dialog.y+dialog.height,'comparison fits the dialog');
  await page.screenshot({path:path.join(require('node:os').tmpdir(),'simulator-distribution.png')});
  await page.locator('#simExplore').click();
  await page.locator('[data-party="06518"]').check();
  const party=await page.locator('[data-new-votes]').textContent();
  assert.match(await page.locator('[data-newcomer]').textContent(),/Distribución provincial de base/);
  await page.locator('#simCircuits').click();
  assert.equal(await page.locator('[data-new-votes]').textContent(),party);
  await page.locator('#simEdit').click();
  assert.equal(await page.locator('#simRepeat').isChecked(),true);
  await page.locator('#simRepeat').uncheck();
  assert.equal(await page.locator('#simComparison').textContent(),original);
  await page.locator('#simRepeat').check();
  await page.locator('#simIncrease').uncheck();
  assert.equal(await page.locator('#simRepeat').isVisible(),false);
  await page.locator('#simIncrease').check();
  assert.equal(await page.locator('#simRepeat').isChecked(),false);
  await page.setViewportSize({width:390,height:844});
  await page.locator('#simRepeat').check();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('#simReset').click();
  assert.equal(await page.locator('#simRepeat').isChecked(),false);
  assert.deepEqual(errors,[]);
  console.log('OK UI: default/visibility, provincial distribution, unavailable target, party/circuit totals, reversibility, persistence, reset and mobile.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
